on:
  schedule:
    - cron: '0 23 * * *'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      uses: joshlarsen/jekyll4-deploy-gh-pages@master
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
        GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
        BRANCH: master
