name: GitHub Actions Build and Deploy
on:
  push:
  schedule:
    - cron: '0 1 * * *'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
      with:
        persist-credentials: false
    - name: Install and Build
      run: |
        gem install jekyll bundler
        bundle exec jekyll serve
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: master
      run: |
        git add . && git commit -m "🚀 update content" && git push git@github.com:nicejade/personal-website.git
