on:
  schedule:
    - cron: '0 1 * * *'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Build
      run: jekyll serve
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: master
